apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twssg
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - trips.arijitdg.net
      secretName: twssg-tls
  rules:
    - host: trips.arijitdg.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: twssg
                port:
                  number: 80
