apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - nginx-configmap.yaml

images:
  - name: twssg
    newName: example.com/twssg
    newTag: placeholder
